version: '3'

networks:
  openhim_openhim:
    driver: bridge

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim_openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - openhim_openhim
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8081:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim_openhim
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim_openhim
    ports:
      - "9000:80"
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
  
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  #   #  OpenCR services
  opencr:
    container_name: opencr
    image: intrahealth/opencr
    ports:
      - "3000:3000"
    depends_on:
      - fhir
      - es
    restart: on-failure
    environment:
      - NODE_ENV=cicd
    networks: 
      - openhim

  fhir:
    container_name: globits-hapi-fhir
    image: globitsvn/globits-hapi-fhir-cs
    ports:
      - "8082:8082"
    networks:
      - openhim_openhim

  es:
    container_name: es
    image: intrahealth/elasticsearch:latest
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - openhim_openhim

    

volumes:
  mongo-data:
  mysql-data:
  # cr-pgdata:
  # cr-orientdata:
  data01:
    driver: local